# Generated by Django 4.1 on 2023-01-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot_server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='answer',
            field=models.CharField(default='test answe', max_length=500),
            preserve_default=False,
        ),
    ]
